-- AUTO-GENERATED by tools/generate_highlat_fixtures.mjs. Do not edit by hand.
-- adhan-js 4.4.4, MuslimWorldLeague, Shafi Asr,
-- HighLatitudeRule.recommended() per city. Values are minute-of-day in UTC.
return {
  meta = { method="MuslimWorldLeague", madhab="Shafi" },
  cities = {
    { name="Rotterdam", lat=51.9244, lon=4.4777, rule="seventhofthenight",
      dates = {
      { date="2026-06-21", fajr=140, sunrise=202, dhuhr=705, asr=968, maghrib=1206, isha=1268 },
      { date="2026-07-15", fajr=154, sunrise=220, dhuhr=709, asr=967, maghrib=1195, isha=1262 },
      { date="2026-12-21", fajr=342, sunrise=467, dhuhr=701, asr=797, maghrib=933, isha=1052 },
      } },
    { name="Stockholm", lat=59.3293, lon=18.0686, rule="seventhofthenight",
      dates = {
      { date="2026-06-21", fajr=45, sunrise=91, dhuhr=651, asr=930, maghrib=1208, isha=1254 },
      { date="2026-07-15", fajr=64, sunrise=117, dhuhr=655, asr=926, maghrib=1189, isha=1242 },
      { date="2026-12-21", fajr=310, sunrise=463, dhuhr=647, asr=702, maghrib=828, isha=981 },
      } },
  },
}
