-- AUTO-GENERATED by tools/generate_fixtures.mjs. Do not edit by hand.
-- Rotterdam (51.9244, 4.4777), MuslimWorldLeague, Shafi Asr.
-- Values are minute-of-day in UTC. adhan-js 4.4.4.
return {
  meta = { city="Rotterdam", method="MuslimWorldLeague", madhab="Shafi",
           lat=51.9244, lon=4.4777 },
  dates = {
  { date="2026-01-15", fajr=341, sunrise=463, dhuhr=712, asr=822, maghrib=961, isha=1076 },
  { date="2026-03-20", fajr=230, sunrise=345, dhuhr=711, asr=908, maghrib=1075, isha=1183 },
  { date="2026-06-21", fajr=1424, sunrise=202, dhuhr=705, asr=968, maghrib=1206, isha=1424 },
  { date="2026-07-15", fajr=1427, sunrise=220, dhuhr=709, asr=967, maghrib=1195, isha=1428 },
  { date="2026-09-23", fajr=215, sunrise=330, dhuhr=695, asr=890, maghrib=1058, isha=1166 },
  { date="2026-12-21", fajr=342, sunrise=467, dhuhr=701, asr=797, maghrib=933, isha=1052 },
  },
}
