// Phase 2b-4 fixture generator (timezone/DST end-to-end).
// Emits adhan-js reference times converted to each city's LOCAL time using
// Node's ICU/IANA database (the authoritative source). The Lua engine +
// Timezone layer must reproduce these local times within +/-1 minute. This is
// what proves our hand-rolled DST and each city's coordinates/offset are right.
//
// Sample spans every offset zone (+0..+7) and both DST observers and
// non-observers, on dates straddling BOTH 2026 transitions plus solstice
// controls. Recommended high-latitude rule, matching the engine's Calculator.
//
// Regenerate with:  node tools/generate_tz_fixtures.mjs

import * as adhan from 'adhan';
import { writeFileSync } from 'node:fs';

const METHOD = 'MuslimWorldLeague';
const MADHAB = 'Shafi';
const PRAYERS = ['fajr', 'sunrise', 'dhuhr', 'asr', 'maghrib', 'isha'];

// Coordinates MUST match data/cities.lua (the runner cross-checks this).
// iana is used ONLY here, to produce the authoritative local-time reference.
const SAMPLE = [
  { name: 'London', iana: 'Europe/London', lat: 51.5074, lon: -0.1278 },        // +0 EU
  { name: 'Paris', iana: 'Europe/Paris', lat: 48.8566, lon: 2.3522 },           // +1 EU
  { name: 'Sarajevo', iana: 'Europe/Sarajevo', lat: 43.8563, lon: 18.4131 },    // +1 EU (Balkans)
  { name: 'Stockholm', iana: 'Europe/Stockholm', lat: 59.3293, lon: 18.0686 },  // +1 EU (high lat)
  { name: 'Athens', iana: 'Europe/Athens', lat: 37.9838, lon: 23.7275 },        // +2 EU
  { name: 'Helsinki', iana: 'Europe/Helsinki', lat: 60.1699, lon: 24.9384 },    // +2 EU (high lat)
  { name: 'Istanbul', iana: 'Europe/Istanbul', lat: 41.0082, lon: 28.9784 },    // +3 none
  { name: 'Moscow', iana: 'Europe/Moscow', lat: 55.7558, lon: 37.6173 },        // +3 none
  { name: 'Ufa', iana: 'Asia/Yekaterinburg', lat: 54.7388, lon: 55.9721 },      // +5 none
  { name: 'Yekaterinburg', iana: 'Asia/Yekaterinburg', lat: 56.8389, lon: 60.6057 }, // +5 none
  { name: 'Novosibirsk', iana: 'Asia/Novosibirsk', lat: 55.0084, lon: 82.9357 },     // +7 none
];

// Both transition boundaries (Sun 29 Mar, Sun 25 Oct 2026) + solstice controls.
const TEST_DATES = ['2026-03-28', '2026-03-29', '2026-10-24', '2026-10-25', '2026-06-21', '2026-12-21'];

const localMinuteOfDay = (date, iana) => {
  const parts = new Intl.DateTimeFormat('en-GB', {
    timeZone: iana, hour: '2-digit', minute: '2-digit', hourCycle: 'h23',
  }).formatToParts(date);
  const h = Number(parts.find((p) => p.type === 'hour').value);
  const m = Number(parts.find((p) => p.type === 'minute').value);
  return h * 60 + m;
};

const samples = SAMPLE.map((c) => {
  const coords = new adhan.Coordinates(c.lat, c.lon);
  const rule = adhan.HighLatitudeRule.recommended(coords);
  const dates = TEST_DATES.map((iso) => {
    const [y, m, d] = iso.split('-').map(Number);
    const params = adhan.CalculationMethod[METHOD]();
    params.madhab = adhan.Madhab[MADHAB];
    params.highLatitudeRule = rule;
    const pt = new adhan.PrayerTimes(coords, new Date(y, m - 1, d), params);
    const prayers = {};
    for (const p of PRAYERS) prayers[p] = localMinuteOfDay(pt[p], c.iana);
    return { date: iso, prayers };
  });
  return { name: c.name, iana: c.iana, lat: c.lat, lon: c.lon, dates };
});

const meta = { method: METHOD, madhab: MADHAB, adhanVersion: '4.4.4',
  note: 'Generated by tools/generate_tz_fixtures.mjs. Local minute-of-day via '
      + 'ICU/IANA. Ground truth for Phase 2b-4 (engine + Timezone).' };

writeFileSync(new URL('../fixtures/tz_local_reference.json', import.meta.url),
  JSON.stringify({ meta, samples }, null, 2) + '\n');

const luaDate = (r) =>
  `      { date="${r.date}", ` + PRAYERS.map((p) => `${p}=${r.prayers[p]}`).join(', ') + ' },';
const luaSample = (s) =>
`    { name="${s.name}", iana="${s.iana}", lat=${s.lat}, lon=${s.lon},
      dates = {
${s.dates.map(luaDate).join('\n')}
      } },`;
writeFileSync(new URL('../fixtures/tz_local_reference.lua', import.meta.url),
`-- AUTO-GENERATED by tools/generate_tz_fixtures.mjs. Do not edit by hand.
-- adhan-js ${meta.adhanVersion}, ${METHOD}, ${MADHAB}, recommended hi-lat rule.
-- Values are LOCAL minute-of-day via ICU/IANA.
return {
  meta = { method="${METHOD}", madhab="${MADHAB}" },
  samples = {
${samples.map(luaSample).join('\n')}
  },
}
`);

console.log(`Wrote tz reference: ${samples.length} cities x ${TEST_DATES.length} dates.`);
