// Phase 3-2 fixture generator: the method x Asr-school x city matrix.
// Produces adhan-js reference prayer times (minute-of-day UTC) for EVERY
// exposed calculation method x {Standard/Shafi, Hanafi} x a small city set
// that spans below and above the 48-degree high-latitude threshold. This is
// the GROUND TRUTH the Lua engine must reproduce within +/-1 minute in
// tools/run_tests.lua. Do NOT hand-edit the output; regenerate with:
//   node tools/generate_methods_fixtures.mjs
//
// The generator mirrors the addon's runtime policy exactly: the high-latitude
// rule is HighLatitudeRule.recommended(coords) (the same default our
// Calculator applies), so the comparison is apples-to-apples per method. That
// is what makes the high-latitude-per-method interaction a real test: a method
// with a shallower Fajr/Isha angle (e.g. ISNA 15) reaches the angle on more
// days than a steep one (e.g. Singapore 20), so the safe-value clamp engages
// differently -- and both sides must still agree.
//
// MoonsightingCommittee is intentionally excluded (ADR-0004): it is a seasonal
// algorithm, not a parameter set, deferred to its own ADR + fixtures.

import * as adhan from 'adhan';
import { writeFileSync } from 'node:fs';

// Every exposed method (order = the UI/registry order we will ship).
const METHODS = [
  'MuslimWorldLeague', 'Egyptian', 'Karachi', 'UmmAlQura', 'Dubai',
  'NorthAmerica', 'Kuwait', 'Qatar', 'Singapore', 'Tehran', 'Turkey', 'Other',
];

const MADHABS = [
  { key: 'shafi', adhan: adhan.Madhab.Shafi },   // Standard
  { key: 'hanafi', adhan: adhan.Madhab.Hanafi },
];

// City set: two below 48 deg, two above (Rotterdam 51.9, Stockholm 59.3) to
// exercise the high-latitude safe-value clamp under every method's angles.
const CITIES = [
  { name: 'Istanbul', latitude: 41.0082, longitude: 28.9784 },
  { name: 'Sarajevo', latitude: 43.8563, longitude: 18.4131 },
  { name: 'Rotterdam', latitude: 51.9244, longitude: 4.4777 },
  { name: 'Stockholm', latitude: 59.3293, longitude: 18.0686 },
];

// Seasonal dates: deep winter, spring equinox, summer solstice (peak clamp).
const TEST_DATES = ['2026-01-15', '2026-03-20', '2026-06-21'];

const PRAYERS = ['fajr', 'sunrise', 'dhuhr', 'asr', 'maghrib', 'isha'];
const minuteOfDayUTC = (d) => d.getUTCHours() * 60 + d.getUTCMinutes();

const rows = [];
for (const cityDef of CITIES) {
  const coords = new adhan.Coordinates(cityDef.latitude, cityDef.longitude);
  const highLat = adhan.HighLatitudeRule.recommended(coords); // mirror Calculator
  for (const methodName of METHODS) {
    for (const madhab of MADHABS) {
      for (const iso of TEST_DATES) {
        const [y, m, d] = iso.split('-').map(Number);
        const params = adhan.CalculationMethod[methodName]();
        params.madhab = madhab.adhan;
        params.highLatitudeRule = highLat;
        // Local-midnight Date so getFullYear/Month/Date == y/m/d on any
        // machine TZ (adhan reads local calendar components); the UTC readout
        // below is TZ-independent. Matches the Phase 1 generator.
        const pt = new adhan.PrayerTimes(coords, new Date(y, m - 1, d), params);
        const cells = {};
        for (const p of PRAYERS) cells[p] = minuteOfDayUTC(pt[p]);
        rows.push({
          city: cityDef.name, lat: cityDef.latitude, lon: cityDef.longitude,
          method: methodName, madhab: madhab.key, date: iso, ...cells,
        });
      }
    }
  }
}

const meta = {
  adhanVersion: '4.4.4',
  highLatitudeRule: 'recommended (>48 deg -> SeventhOfTheNight, else MiddleOfTheNight)',
  methods: METHODS, madhabs: MADHABS.map((m) => m.key),
  cities: CITIES, dates: TEST_DATES,
  note: 'Generated by tools/generate_methods_fixtures.mjs. Ground truth for '
      + 'Phase 3 (method x Asr x city). Values are minute-of-day in UTC. '
      + 'MoonsightingCommittee excluded per ADR-0004.',
};

writeFileSync(
  new URL('../fixtures/methods_matrix.json', import.meta.url),
  JSON.stringify({ meta, rows }, null, 2) + '\n',
);

// Lua: loadable by the LuaJIT runner without a JSON library.
const luaRow = (r) => {
  const cols = PRAYERS.map((p) => `${p}=${r[p]}`).join(', ');
  return `  { city="${r.city}", lat=${r.lat}, lon=${r.lon}, method="${r.method}", `
       + `madhab="${r.madhab}", date="${r.date}", ${cols} },`;
};
const lua =
`-- AUTO-GENERATED by tools/generate_methods_fixtures.mjs. Do not edit by hand.
-- Method x Asr-school x city matrix. Values are minute-of-day in UTC.
-- adhan-js ${meta.adhanVersion}; high-latitude rule = recommended().
-- MoonsightingCommittee excluded per ADR-0004.
return {
  meta = { adhanVersion="${meta.adhanVersion}", count=${rows.length} },
  rows = {
${rows.map(luaRow).join('\n')}
  },
}
`;
writeFileSync(new URL('../fixtures/methods_matrix.lua', import.meta.url), lua);

console.log(`Wrote ${rows.length} rows: ${METHODS.length} methods x `
  + `${MADHABS.length} madhabs x ${CITIES.length} cities x ${TEST_DATES.length} dates.`);
