// Phase 1 fixture generator.
// Produces adhan-js reference prayer times for Rotterdam (MWL, Standard Asr)
// on a fixed set of test dates. This output is the GROUND TRUTH the Lua
// engine must reproduce within +/-1 minute. Do NOT hand-edit the fixtures;
// regenerate with:  TZ=Europe/Amsterdam node tools/generate_fixtures.mjs
//
// Determinism: run pinned to TZ=Europe/Amsterdam so local date components and
// the human-readable local times are stable regardless of machine timezone.

import * as adhan from 'adhan';
import { writeFileSync } from 'node:fs';

const CITY = { name: 'Rotterdam', latitude: 51.9244, longitude: 4.4777 };
const METHOD = 'MuslimWorldLeague';
const MADHAB = 'Shafi'; // Standard Asr
const TZ = 'Europe/Amsterdam';

// Fixed test dates (year 2026): equinoxes, solstices, and extra summer/winter
// points that stress the high latitude of Rotterdam (51.9N).
const TEST_DATES = [
  '2026-01-15', // deep winter
  '2026-03-20', // spring equinox
  '2026-06-21', // summer solstice  <-- PO sanity check
  '2026-07-15', // high summer
  '2026-09-23', // autumn equinox
  '2026-12-21', // winter solstice   <-- PO sanity check
];

const PRAYERS = ['fajr', 'sunrise', 'dhuhr', 'asr', 'maghrib', 'isha'];

const coords = new adhan.Coordinates(CITY.latitude, CITY.longitude);
const params = adhan.CalculationMethod[METHOD]();
params.madhab = adhan.Madhab[MADHAB];

const fmtLocal = new Intl.DateTimeFormat('en-GB', {
  timeZone: TZ, hour: '2-digit', minute: '2-digit', hour12: false,
});
const fmtUTC = (d) =>
  `${String(d.getUTCHours()).padStart(2, '0')}:${String(d.getUTCMinutes()).padStart(2, '0')}`;
const minuteOfDayUTC = (d) => d.getUTCHours() * 60 + d.getUTCMinutes();

const results = TEST_DATES.map((iso) => {
  const [y, m, d] = iso.split('-').map(Number);
  const date = new Date(y, m - 1, d); // local midnight in TZ
  const pt = new adhan.PrayerTimes(coords, date, params);
  const prayers = {};
  for (const p of PRAYERS) {
    const t = pt[p];
    prayers[p] = {
      local: fmtLocal.format(t),         // human-readable Europe/Amsterdam
      utc: fmtUTC(t),                    // UTC HH:MM
      minuteOfDayUTC: minuteOfDayUTC(t), // engine compares on this
      epoch: Math.floor(t.getTime() / 1000),
    };
  }
  return { date: iso, prayers };
});

const meta = {
  city: CITY, method: METHOD, madhab: MADHAB, timezone: TZ,
  adhanVersion: '4.4.4',
  note: 'Generated by tools/generate_fixtures.mjs. Ground truth for Phase 1. '
      + 'Engine compares on minuteOfDayUTC (UTC avoids DST ambiguity in Lua).',
};

// JSON: human/diff-friendly.
writeFileSync(
  new URL('../fixtures/rotterdam_mwl_standard.json', import.meta.url),
  JSON.stringify({ meta, dates: results }, null, 2) + '\n',
);

// Lua: loadable by the LuaJIT test runner without a JSON library.
const luaDate = (r) => {
  const cols = PRAYERS.map((p) =>
    `${p}=${r.prayers[p].minuteOfDayUTC}`).join(', ');
  return `  { date="${r.date}", ${cols} },`;
};
const lua =
`-- AUTO-GENERATED by tools/generate_fixtures.mjs. Do not edit by hand.
-- Rotterdam (${CITY.latitude}, ${CITY.longitude}), ${METHOD}, ${MADHAB} Asr.
-- Values are minute-of-day in UTC. adhan-js ${meta.adhanVersion}.
return {
  meta = { city="${CITY.name}", method="${METHOD}", madhab="${MADHAB}",
           lat=${CITY.latitude}, lon=${CITY.longitude} },
  dates = {
${results.map(luaDate).join('\n')}
  },
}
`;
writeFileSync(
  new URL('../fixtures/rotterdam_mwl_standard.lua', import.meta.url),
  lua,
);

// Console summary for the Product Owner sanity check.
console.log(`Rotterdam | ${METHOD} | ${MADHAB} Asr | local times (${TZ})\n`);
const pad = (s, n) => String(s).padEnd(n);
console.log(pad('date', 12) + PRAYERS.map((p) => pad(p, 9)).join(''));
for (const r of results) {
  console.log(pad(r.date, 12) +
    PRAYERS.map((p) => pad(r.prayers[p].local, 9)).join(''));
}
