// Phase 2a fixture generator (high-latitude rule).
// Produces adhan-js reference prayer times WITH HighLatitudeRule.recommended()
// applied, for high-latitude cities. This is the ground truth for 2a: it
// proves usable summer Fajr/Isha (no midnight clamp). The Phase 1 generator
// and fixtures (rotterdam_mwl_standard.*) are NOT touched and remain the
// regression guard for the engine's bare default path.
//
// Regenerate with:  TZ=UTC node tools/generate_highlat_fixtures.mjs

import * as adhan from 'adhan';
import { writeFileSync } from 'node:fs';

const METHOD = 'MuslimWorldLeague';
const MADHAB = 'Shafi'; // Standard Asr

const CITIES = [
  { name: 'Rotterdam', latitude: 51.9244, longitude: 4.4777, tz: 'Europe/Amsterdam' },
  { name: 'Stockholm', latitude: 59.3293, longitude: 18.0686, tz: 'Europe/Stockholm' },
];

// Summer dates (where the clamp appeared) plus a winter control.
const TEST_DATES = ['2026-06-21', '2026-07-15', '2026-12-21'];

const PRAYERS = ['fajr', 'sunrise', 'dhuhr', 'asr', 'maghrib', 'isha'];

const fmtLocal = (tz) => new Intl.DateTimeFormat('en-GB', {
  timeZone: tz, hour: '2-digit', minute: '2-digit', hour12: false,
});
const minuteOfDayUTC = (d) => d.getUTCHours() * 60 + d.getUTCMinutes();

const cityResults = CITIES.map((city) => {
  const coords = new adhan.Coordinates(city.latitude, city.longitude);
  const rule = adhan.HighLatitudeRule.recommended(coords);
  const local = fmtLocal(city.tz);
  const dates = TEST_DATES.map((iso) => {
    const [y, m, d] = iso.split('-').map(Number);
    const params = adhan.CalculationMethod[METHOD]();
    params.madhab = adhan.Madhab[MADHAB];
    params.highLatitudeRule = rule;
    const pt = new adhan.PrayerTimes(coords, new Date(y, m - 1, d), params);
    const prayers = {};
    for (const p of PRAYERS) {
      prayers[p] = { local: local.format(pt[p]), minuteOfDayUTC: minuteOfDayUTC(pt[p]) };
    }
    return { date: iso, prayers };
  });
  return { name: city.name, latitude: city.latitude, longitude: city.longitude,
           timezone: city.tz, rule, dates };
});

const meta = {
  method: METHOD, madhab: MADHAB, adhanVersion: '4.4.4',
  rule: 'HighLatitudeRule.recommended() per city',
  note: 'Generated by tools/generate_highlat_fixtures.mjs. Ground truth for '
      + 'Phase 2a. Engine compares on minuteOfDayUTC.',
};

writeFileSync(
  new URL('../fixtures/highlat_recommended.json', import.meta.url),
  JSON.stringify({ meta, cities: cityResults }, null, 2) + '\n',
);

// Lua: loadable by the LuaJIT test runner.
const luaDate = (r) =>
  `      { date="${r.date}", `
  + PRAYERS.map((p) => `${p}=${r.prayers[p].minuteOfDayUTC}`).join(', ') + ' },';
const luaCity = (c) =>
`    { name="${c.name}", lat=${c.latitude}, lon=${c.longitude}, rule="${c.rule}",
      dates = {
${c.dates.map(luaDate).join('\n')}
      } },`;
const lua =
`-- AUTO-GENERATED by tools/generate_highlat_fixtures.mjs. Do not edit by hand.
-- adhan-js ${meta.adhanVersion}, ${METHOD}, ${MADHAB} Asr,
-- HighLatitudeRule.recommended() per city. Values are minute-of-day in UTC.
return {
  meta = { method="${METHOD}", madhab="${MADHAB}" },
  cities = {
${cityResults.map(luaCity).join('\n')}
  },
}
`;
writeFileSync(
  new URL('../fixtures/highlat_recommended.lua', import.meta.url),
  lua,
);

// Console summary for the Product Owner sanity check.
for (const c of cityResults) {
  console.log(`\n${c.name} (${c.latitude}N)  rule=${c.rule}  [local ${c.timezone}]`);
  const pad = (s, n) => String(s).padEnd(n);
  console.log('  ' + pad('date', 12) + PRAYERS.map((p) => pad(p, 9)).join(''));
  for (const r of c.dates) {
    console.log('  ' + pad(r.date, 12) + PRAYERS.map((p) => pad(r.prayers[p].local, 9)).join(''));
  }
}
